Only completed debugging
learn-academy-2022-foxtrot/week-3-assessment-letkyle pull request #1
Opened 2022-09-26 15:19 UTC by letkyle

# Submitting Week 3 Assessment

### ✅ Completed Files

Mark the following as confirmation that the files in this repository are complete.

- [ ] Coding Challenges
- [ ] Interview Questions
- [x] React Debugging

### 📝 Feedback

If you would like specific feedback on a particular problem please leave details here:
I still need to finish my coding challenges and add better pseudo coding, and still need to finish interview questions.

2022-09-27 20:13 UTC, elysemontano requested changes
Request changes:  Looks like you are missing researched answers in the interview questions section. Please update this section and I will review this PR.

2022-09-30 21:47 UTC, letkyle commented
just finished the researched answers in the interview questions section.

2022-09-30 21:49 UTC, merged

2022-09-30 21:59 UTC, elysemontano reviewed
I don't see any pseudocode for problems 2 and 3 in code challenges.  Please update this and I will consider this approved.

2022-09-30 21:59 UTC, elysemontano commented on code-challenges.test.js
> +        let filteredArr = object.filter(value => typeof value === "number")
Filter only works on arrays and not on objects.  I would recommend checking the resource provided that would help with that step to get your test pass.

2022-09-30 21:59 UTC, elysemontano commented on code-challenges.test.js
> +    }
I don't see any pseudocode for this problem and problem 2.